name: Cucumber CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: build-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            build-${{ runner.os }}-maven-
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"      - name: Run Maven Tests
        run: |
          cd maven
          # Install Xvfb for headless browser testing
          sudo apt-get update
          sudo apt-get install -y xvfb
          # Run tests with headless browser
          xvfb-run -a ./mvnw clean test -Dheadless=true
      - name: Check test results
        run: |
          echo "Checking test execution results..."
          cd maven
          if [ -f target/surefire-reports/TEST-io.cucumber.a4.runner.RunCucumberTest.xml ]; then
            echo "✅ Tests completed successfully"
            echo "XML report found"
          else
            echo "❌ Test XML report not found"
            echo "Available files in surefire-reports:"
            ls -la target/surefire-reports/ 2>/dev/null || echo "No surefire-reports directory found"
            exit 1
          fi
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            maven/target/surefire-reports/
            maven/target/cucumber-reports/
